weaves

This is for Revolut. Part II of Challenge

This uses the output of anal2.q to predict an unengaged user.
Analysis uses a simplified users table.

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import cross_val_score
from sklearn.feature_selection import RFE

from sklearn.preprocessing import StandardScaler

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelBinarizer

from sklearn import svm
from sklearn import datasets

%load_ext autoreload
%autoreload 2

pd.__version__

'0.24.2'

In [2]:
from sklearn import datasets

from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

# load the iris datasets
dataset = datasets.load_iris()
# create a base classifier used to evaluate a subset of attributes
model = LogisticRegression()
# create the RFE model and select 3 attributes
rfe = RFE(model, 3)
rfe = rfe.fit(dataset.data, dataset.target)
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)

[False  True  True  True]
[2 1 1 1]


/misc/share/0/anaconda3/envs/gensim/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/misc/share/0/anaconda3/envs/gensim/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/misc/share/0/anaconda3/envs/gensim/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/misc/share/0/anaconda3/envs/gensim/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [3]:
# Read the CSV. This has been written out by q/kdb+. Booleans were converted by q/kdb+
# The userid is the index.
df0 = pd.read_csv('cache/out/xusers1.csv', index_col=0)

In [4]:
df0.head()

ctry  uscrypt0      plan  push1  email1  ncontacts  age0  lost0  nico0  \
userid                                                                          
0        PL      True  STANDARD      1       1          3    30  False  False   
1        GB     False  STANDARD     -1      -1         21    44  False   True   
2        PL     False  STANDARD      0       0         21    32  False  False   
3        FR     False  STANDARD      1       0          0    25  False  False   
4        GB     False  STANDARD     -1      -1          2    34  False  False   

        nicu0  ...  tdecl  tfail  tpend  trvrt   inb    brand       v  \
userid         ...                                                      
0       False  ...   True   True  False   True  True    Apple   36.14   
1        True  ...   True  False  False   True  True    Apple   50.05   
2       False  ...   True   True  False   True  True  Android   12.66   
3       False  ...  False  False   True   True  True    Apple   64.57   
4       False  ...  False  False  False   True  True    Apple  203.99   

        nactive  inactive inactive1  
userid                               
0         False     False     False  
1         False     False     False  
2         False     False     False  
3         False     False     False  
4         False     False     False  

[5 rows x 24 columns]

In [5]:
# Most fields are string
df0.columns.to_series().groupby(df0.dtypes).groups

{dtype('bool'): Index(['uscrypt0', 'lost0', 'nico0', 'nicu0', 'nifpco0', 'otau0', 'pf0',
        'tcncl', 'tdecl', 'tfail', 'tpend', 'trvrt', 'inb', 'nactive',
        'inactive', 'inactive1'],
       dtype='object'),
 dtype('int64'): Index(['push1', 'email1', 'ncontacts', 'age0'], dtype='object'),
 dtype('float64'): Index(['v'], dtype='object'),
 dtype('O'): Index(['ctry', 'plan', 'brand'], dtype='object')}

## Outcomes: 3 types of unengagedness

There are three types of unengaged user, where a user is one that has no activity

- at all. Labelled as nactive. No transactions from 2018.01.01. Do not use the average value of transactions as a feature it's always zero.
- in the last year. Labelled as inactive. Last activity was over a year ago. The average value is 0 for 60% so not too useful
- over a month ago. Labelled as inactive1. Average value is 0 for 30% of this population.

In [6]:
df0[df0.select_dtypes(['object']).columns] = df0.select_dtypes(['object']).apply(lambda x: x.astype('category'))

In [7]:
# The groups phrase doesn't work for category
df0.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19430 entries, 0 to 19429
Data columns (total 24 columns):
ctry         19430 non-null category
uscrypt0     19430 non-null bool
plan         19430 non-null category
push1        19430 non-null int64
email1       19430 non-null int64
ncontacts    19430 non-null int64
age0         19430 non-null int64
lost0        19430 non-null bool
nico0        19430 non-null bool
nicu0        19430 non-null bool
nifpco0      19430 non-null bool
otau0        19430 non-null bool
pf0          19430 non-null bool
tcncl        19430 non-null bool
tdecl        19430 non-null bool
tfail        19430 non-null bool
tpend        19430 non-null bool
trvrt        19430 non-null bool
inb          19430 non-null bool
brand        19430 non-null category
v            19430 non-null float64
nactive      19430 non-null bool
inactive     19430 non-null bool
inactive1    19430 non-null bool
dtypes: bool(16), category(3), float64(1), int64(4)
memory usage: 1.2 MB


In [8]:
# Store the categories
cats0 = dict([ (x, tuple(df0[x].cat.categories)) for x in df0.select_dtypes(['category']).columns ])
cats0

{'ctry': ('AT',
  'AU',
  'BE',
  'BG',
  'CH',
  'CY',
  'CZ',
  'DE',
  'DK',
  'EE',
  'ES',
  'FI',
  'FR',
  'GB',
  'GF',
  'GG',
  'GI',
  'GP',
  'GR',
  'HR',
  'HU',
  'IE',
  'IM',
  'IS',
  'IT',
  'JE',
  'LI',
  'LT',
  'LU',
  'LV',
  'MQ',
  'MT',
  'NL',
  'NO',
  'PL',
  'PT',
  'RE',
  'RO',
  'SE',
  'SI',
  'SK'),
 'plan': ('METAL',
  'METAL_FREE',
  'PREMIUM',
  'PREMIUM_FREE',
  'PREMIUM_OFFER',
  'STANDARD'),
 'brand': ('Android', 'Apple', 'Unknown')}

### Reload the dataset for the model

You need to run this after you have chosen and evaluated.

In [18]:
# Make a copy and quantify the categories by using the category codes.
df2 = df0.copy(deep=True)
df2[df2.select_dtypes(['category']).columns] = df2.select_dtypes(['category']).apply(lambda x: x.cat.codes)
if 'y' in globals():
    del globals()['y']

### Case 1: Never active

Evaluate one of these data cases - that is, re-evaluate the cell above and then Case 1 *or* Case 2 *or* Case 3.

This case Remove value, and inbound transactions

In [10]:
# And obtain the outcome as y. And the features as X, drop columns and rows that would confuse the model.

y = df2.nactive
df2.drop(columns=['nactive', 'inactive', 'inactive1', 'v', 'inb'], inplace=True)
# Note: this uses the values property to get the underlying matrix.
X = df2.values

### Case 2: Inactive

Remove value (for now), but keep inb.
Remove nactive samples.

In [11]:
if not 'y' in globals():
    df2 = df2[~df2['nactive']]
    y = df2.inactive
    df2.drop(columns=['inactive', 'nactive', 'inactive1', 'v'], inplace=True)
    X = df2.values

### Case 3: Inactive

Keep value and inb

In [19]:
# And obtain the outcome as y. And the features as X
# Note: this uses the values property to get the underlying matrix.
if not 'y' in globals():
    df2 = df2[~df2['nactive']]
    df2 = df2[~df2['inactive']]
    y = df2.inactive1
    df2.drop(columns=['inactive1', 'nactive', 'inactive1'], inplace=True)
    X = df2.values

## Model cases

Again choose one to apply to the data you've chosen.

These are a couple of models to evaluate.

The first SVC is not practical for "big" data (width and count), but works well for smaller ones.

The Multi-Layer Perceptron Classifier is a useful neural network and can get reasonable results quickly - it parallizes well. The hidden_layer_sizes need tuning to get a cross validation score over 0.5.

The logistic regression is a very solid performer.

In [13]:
clf = svm.SVC(kernel='linear', C=1)

In [14]:
clf =  MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(X.shape[1], X.shape[1], 2), 
                     random_state=1, warm_start=True)

In [20]:
clf = LogisticRegression(C=1e4, solver='lbfgs', multi_class='auto', max_iter=10000) # max_iter is 2 orders up!

## From cross-validation results, choose the most accurate model

To evaluate the model under a cross-validation scheme, run this cell.

In [21]:
scores = cross_val_score(clf, X, y, cv=5)
scores

array([0.79788419, 0.79003063, 0.79866332, 0.81592871, 0.79359331])

## Feature selection

Try to determine best features

In [22]:
# create the RFE model and select 3 attributes
rfe = RFE(clf, 5)
rfe = rfe.fit(X, y)
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)
df2.columns[rfe.support_]

[False False False False False False False False False False False  True
 False False  True False  True  True  True False False False]
[15  9  5  8  7 14 16  6 12 11  4  1 10  2  1  3  1  1  1 13 17 18]


Index(['otau0', 'tdecl', 'tpend', 'trvrt', 'inb'], dtype='object')

# Summary

Case 1. Never active. The models all fit quickly and over cross-validation manage to get to over 90% accuracy.
Only MLPC struggles.

Case 2. Inactive for over a year. SVM really struggles to converge. Logistic regression needs 10000 iterations but gets to over 90%. MLPC gets there but is probably over-fitting.

Case 3. Inactive for over a month. MLCP gets 30% with full full layers. Logistic regression can get to over 75%.

Running through the models, and looking at the feature selection, it seems that, for all cases, if a user has had transaction declined, or has had one reverted or declared as pending, then they prove to be inactive. For some reason a notification of ONBOARDING_TIPS_ACTIVATED_USERS seems to be a good indicator. This might be that account-holders who are having trouble ask for help in the form of onboarding tips.